const hostURI = "http://localhost:3000";
export const v1ApiRootUrl = hostURI + "/api/v1";
export const EXPENSE_TYPE_ENUM = [
  "Games",
  "Movies",
  "Music",
  "Sports",
  "Dining Out",
  "Groceries",
  "Liquor",
  "Electronics",
  "Furniture",
  "Rent",
  "Pets",
  "Maintenance",
  "Childcare",
  "Taxes",
  "Clothing",
  "Education",
  "Gifts",
  "Medical",
  "Insurance",
  "Bus",
  "Train",
  "Car",
  "Fuel",
  "Hotel",
  "Praking",
  "Taxi",
  "Flight",
  "General",
  "WIFI/Internet",
  "Water",
  "Electricty",
  "Heat",
  "Cleaning",
  "Trash",
];
